import{precheckCandidates}from'./src/catalog.mjs';
const $=s=>document.querySelector(s),num=new Intl.NumberFormat('ja-JP'),yen=new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}),PAGE=48;
const labels={read:'読了',reading:'読書中',unread:'未読',untracked:'未登録'},colors={read:'#0f766e',reading:'#b7791f',unread:'#4f6fa6',untracked:'#94a3b8'},palettes=['#e6ece8','#ede8df','#e8e7ef','#e7ecef','#efe6e2','#e9eadf','#e5ede9','#ece7e1'];
const state={catalog:null,filtered:[],query:'',statuses:new Set,categories:new Set,sources:new Set,sort:'acquired-desc',view:'grid',page:1};
async function loadCatalog(){const m=await fetch('./data/catalog.parts.json').then(r=>r.json()),parts=await Promise.all(m.parts.map(p=>fetch(`./data/${p}`).then(r=>r.text()))),bin=atob(parts.join('').replace(/\s/g,'')),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0)),stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip')),c=await new Response(stream).json();const works=c.w.map(([work_id,title,title_key,category,status,progress,rating,price_yen,acquired_at,item_count,sources,formats])=>({work_id,title,title_key,author:null,category,status,progress,rating,price_yen,acquired_at,item_count,isbn_count:0,isbn_status:'missing',sources,formats})),editions=works.map(w=>({edition_id:`pending:${w.work_id.slice(4)}`,id_kind:'pending_title_key',work_id:w.work_id,isbn13:null,verification:'unverified'})),holdings=works.flatMap(w=>w.sources.map((source,i)=>({holding_id:`${w.work_id}:h${i+1}`,work_id:w.work_id,edition_id:`pending:${w.work_id.slice(4)}`,source,format:w.formats[i]??w.formats[0]??'不明',quantity:i?1:w.item_count,acquired_at:w.acquired_at,price_yen:i?null:w.price_yen,progress:i?null:w.progress,rating:i?null:w.rating})));return{schema_version:c.v,generated_at:c.g,stats:{...c.s,edition_count:editions.length,holding_count:holdings.length},works,editions,holdings}}
function fromUrl(){const p=new URLSearchParams(location.search);state.query=p.get('q')??'';state.statuses=new Set(p.getAll('status'));state.categories=new Set(p.getAll('category'));state.sources=new Set(p.getAll('source'));state.sort=p.get('sort')??'acquired-desc';state.view=p.get('view')==='list'?'list':'grid';state.page=Math.max(1,Number(p.get('page')??1))}
function syncUrl(){const p=new URLSearchParams;if(state.query)p.set('q',state.query);for(const x of state.statuses)p.append('status',x);for(const x of state.categories)p.append('category',x);for(const x of state.sources)p.append('source',x);if(state.sort!=='acquired-desc')p.set('sort',state.sort);if(state.view!=='grid')p.set('view',state.view);if(state.page>1)p.set('page',state.page);history.replaceState(null,'',`${location.pathname}${p.size?'?'+p:''}`)}
function counts(field){const m=new Map;for(const w of state.catalog.works)for(const v of(Array.isArray(w[field])?w[field]:[w[field]]))if(v)m.set(v,(m.get(v)||0)+1);return m}
const esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function checks(el,entries,set,label=x=>x){el.innerHTML='';for(const[value,count]of entries){const row=document.createElement('label');row.className='check-row';row.innerHTML=`<input type="checkbox" value="${esc(value)}" ${set.has(value)?'checked':''}><span>${esc(label(value))}</span><em>${num.format(count)}</em>`;row.querySelector('input').onchange=e=>{e.target.checked?set.add(value):set.delete(value);state.page=1;apply()};el.append(row)}}
function setup(){checks($('#statusFilters'),Object.entries(counts('status')),state.statuses,v=>labels[v]);checks($('#categoryFilters'),[...counts('category')].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ja')),state.categories);checks($('#sourceFilters'),[...counts('sources')].sort((a,b)=>b[1]-a[1]),state.sources);$('#searchInput').value=state.query;$('#sortSelect').value=state.sort;setView(state.view)}
function apply(){const q=state.query.normalize('NFKC').toLocaleLowerCase('ja').trim();state.filtered=state.catalog.works.filter(w=>{const h=[w.title,w.category,...w.sources].join(' ').normalize('NFKC').toLocaleLowerCase('ja');return(!q||h.includes(q))&&(!state.statuses.size||state.statuses.has(w.status))&&(!state.categories.size||state.categories.has(w.category))&&(!state.sources.size||w.sources.some(x=>state.sources.has(x)))});const rank={read:4,reading:3,unread:2,untracked:1};state.filtered.sort((a,b)=>state.sort==='title-asc'?a.title.localeCompare(b.title,'ja'):state.sort==='rating-desc'?(b.rating??-1)-(a.rating??-1)||a.title.localeCompare(b.title,'ja'):state.sort==='price-desc'?(b.price_yen??-1)-(a.price_yen??-1)||a.title.localeCompare(b.title,'ja'):state.sort==='status-desc'?rank[b.status]-rank[a.status]||a.title.localeCompare(b.title,'ja'):state.sort==='items-desc'?b.item_count-a.item_count||a.title.localeCompare(b.title,'ja'):(b.acquired_at??'').localeCompare(a.acquired_at??'')||a.title.localeCompare(b.title,'ja'));state.page=Math.min(state.page,Math.max(1,Math.ceil(state.filtered.length/PAGE)));render();chips();pages();syncUrl()}
function cover(w){let h=0;for(const c of w.title_key)h=(h*31+c.charCodeAt(0))|0;return palettes[Math.abs(h)%palettes.length]}
function card(w,i){const b=document.createElement('button');b.type='button';b.className='book-card';b.setAttribute('aria-label',`${w.title}の詳細を見る`);b.innerHTML=`<div class="book-cover" style="--cover:${cover(w)}"><div class="cover-inner"><span class="cover-category">${esc(w.category)}</span><strong class="cover-title">${esc(w.title)}</strong><span class="cover-index">KAFKA / ${String(i+1).padStart(3,'0')}</span></div></div><div class="book-meta"><h3>${esc(w.title)}</h3><div class="meta-row"><span class="status-dot" style="--status-color:${colors[w.status]}">${labels[w.status]}</span>${w.item_count>1?`<span class="count-badge">${w.item_count}件統合</span>`:'<span></span>'}</div></div>`;b.onclick=()=>detail(w);return b}
function render(){const g=$('#bookGrid');g.innerHTML='';g.classList.toggle('is-list',state.view==='list');const start=(state.page-1)*PAGE;state.filtered.slice(start,start+PAGE).forEach((w,i)=>g.append(card(w,start+i)));$('#resultCount').textContent=num.format(state.filtered.length);$('#emptyState').hidden=!!state.filtered.length}
function chips(){const v=[];if(state.query)v.push(`検索: ${state.query}`);for(const x of state.statuses)v.push(labels[x]);for(const x of state.categories)v.push(x);for(const x of state.sources)v.push(x);$('#activeFilters').innerHTML=v.map(x=>`<span class="filter-chip">${esc(x)}</span>`).join('')}
function pages(){const total=Math.ceil(state.filtered.length/PAGE),nav=$('#pagination');nav.innerHTML='';if(total<=1)return;for(const p of[...new Set([1,total,state.page-1,state.page,state.page+1])].filter(x=>x>=1&&x<=total).sort((a,b)=>a-b)){const b=document.createElement('button');b.type='button';b.className='page-button';b.textContent=p;if(p===state.page)b.setAttribute('aria-current','page');b.onclick=()=>{state.page=p;apply();$('#catalog').scrollIntoView()};nav.append(b)}}
function detail(w){const h=state.catalog.holdings.filter(x=>x.work_id===w.work_id),e=state.catalog.editions.filter(x=>x.work_id===w.work_id);$('#detailContent').innerHTML=`<div class="detail-layout"><div class="detail-cover" style="--cover:${cover(w)}">${esc(w.title)}</div><div class="detail-info"><p class="eyebrow">${esc(w.category)}</p><h2>${esc(w.title)}</h2><p class="detail-lead">巻・版・登録元をまとめた作品単位の表示です。</p><div class="detail-tags"><span>${labels[w.status]}</span><span>${w.item_count}入力を統合</span>${w.sources.map(x=>`<span>${esc(x)}</span>`).join('')}</div><table class="detail-table"><tbody><tr><th>Work ID</th><td><code>${w.work_id}</code></td></tr><tr><th>読書進捗</th><td>${w.progress==null?'未登録':Math.round(w.progress*100)+'%'}</td></tr><tr><th>評価</th><td>${w.rating==null?'未登録':w.rating.toFixed(1)+' / 5'}</td></tr><tr><th>価格</th><td>${w.price_yen==null?'未登録':yen.format(w.price_yen)}</td></tr><tr><th>形式</th><td>${w.formats.map(esc).join(' / ')}</td></tr><tr><th>登録元</th><td>${h.map(x=>`${esc(x.source)} × ${x.quantity}`).join('<br>')}</td></tr></tbody></table><div class="isbn-callout"><strong>${w.isbn_count?w.isbn_count+' ISBN':'ISBN 未確認'}</strong><span>${e[0]?.edition_id??'版レコードなし'} · 書名からISBNを推測しません。</span></div></div></div>`;$('#detailDialog').showModal()}
function metrics(){const s=state.catalog.stats,t=s.read_count+s.reading_count+s.unread_count;$('#metricWorks').textContent=num.format(s.work_count);$('#metricRead').textContent=num.format(s.read_count);$('#metricReadRate').textContent=t?`状態登録分の ${Math.round(s.read_count/t*100)}%`:'—';$('#metricMerged').textContent=num.format(s.merged_input_count);$('#metricIsbn').textContent=num.format(s.isbn_verified_count);$('#metricSpend').textContent=yen.format(s.known_spend_yen)}
function setView(v){state.view=v;$('#gridButton').classList.toggle('is-active',v==='grid');$('#listButton').classList.toggle('is-active',v==='list');$('#gridButton').setAttribute('aria-pressed',v==='grid');$('#listButton').setAttribute('aria-pressed',v==='list');if(state.catalog){render();syncUrl()}}
function csv(){const hs=['work_id','title','category','status','progress','rating','price_yen','item_count','isbn_status','sources'],rows=state.filtered.map(w=>hs.map(k=>k==='sources'?w.sources.join('|'):w[k]??'')),q=v=>`"${String(v).replaceAll('"','""')}"`,blob=new Blob(['\uFEFF'+[hs,...rows].map(r=>r.map(q).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=Object.assign(document.createElement('a'),{href:u,download:'kafka-books.csv'});a.click();URL.revokeObjectURL(u)}
function precheck(){const box=$('#precheckResults');try{const c=JSON.parse($('#precheckInput').value);if(!Array.isArray(c))throw new TypeError('JSON配列を入力してください。');const r=precheckCandidates(c,state.catalog);$('#precheckSummary').textContent=`${r.summary.allowed}件許可 / ${r.summary.blocked}件停止`;box.innerHTML=r.results.map(x=>`<article class="precheck-result ${x.ok?(x.warnings.length?'is-warning':''):'is-blocked'}"><header><strong>${x.ok?(x.action==='add_edition'?'版を追加可能':'新規作品として追加可能'):'追加停止'}</strong><code>${x.isbn13??'ISBNなし'}</code></header><div>${esc(x.normalized_title||'書名なし')}</div>${[...x.errors,...x.warnings].length?`<ul>${[...x.errors,...x.warnings].map(m=>`<li>${esc(m)}</li>`).join('')}</ul>`:''}</article>`).join('')}catch(e){$('#precheckSummary').textContent='入力エラー';box.innerHTML=`<article class="precheck-result is-blocked">${esc(e.message)}</article>`}}
function events(){let timer;$('#searchInput').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{state.query=e.target.value.trim();state.page=1;apply()},120)};$('#sortSelect').onchange=e=>{state.sort=e.target.value;state.page=1;apply()};$('#gridButton').onclick=()=>setView('grid');$('#listButton').onclick=()=>setView('list');$('#csvButton').onclick=csv;$('#resetButton').onclick=()=>{state.query='';state.statuses.clear();state.categories.clear();state.sources.clear();state.sort='acquired-desc';state.page=1;setup();apply()};$('#detailClose').onclick=()=>$('#detailDialog').close();$('#precheckButton').onclick=()=>$('#precheckDialog').showModal();$('#precheckClose').onclick=()=>$('#precheckDialog').close();$('#runPrecheck').onclick=precheck;document.onkeydown=e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#searchInput').focus()}};document.querySelectorAll('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)d.close()})}
try{fromUrl();state.catalog=await loadCatalog();metrics();setup();events();apply()}catch(e){console.error(e);$('#bookGrid').innerHTML=`<div class="empty-state"><strong>データを読み込めませんでした</strong><p>${esc(e.message)}</p></div>`}